### PR TITLE
Support R8 proguard mapping file

### PR DESCRIPTION
**Pull request by porum**

### CODE REVIEW

**Comment by durganmcbroom** [comment]
Thanks for the commit, have you found an official R8 or proguard spec? I wrote the original parser off of an example i found and thats defintely not sufficient...

On that note, i noticed you changed the lnStart/End to nullable Ints, is there a case where those wont be present in an actual mapping file?

Btw im on vacation, and will have zero internet access for the next 4-5 days so wont be able check or merge anything.

**Comment by panda912** [comment]
[Here](https://github.com/Guardsquare/proguard) is the proguard offical repository.
Method regex are based on https://github.com/Guardsquare/proguard/blob/6dfa0ca00e090d8343f7f8359d5f2fb6850fb69b/base/src/main/java/proguard/obfuscate/MappingReader.java#L150-L153

**Comment by porum** [comment]
Okey, have fun~

[Here](https://github.com/Guardsquare/proguard) is the proguard offical repository.
Method regex are based on https://github.com/Guardsquare/proguard/blob/6dfa0ca00e090d8343f7f8359d5f2fb6850fb69b/base/src/main/java/proguard/obfuscate/MappingReader.java#L150-L153

**Comment by durganmcbroom** [comment]
Sorry for the long wait! Everything here looks good!

In the future it may be a good idea to abstract the MappedNode sub classes into parser specific data classes(again just looking at some of the muability which you introduced, needed for proguard but possibly not for other formats.)

**Pull request merged**
